### ISSUE TITLE
cape not showing

### ISSUE THREAD

**Issue by sak1rro** [CaelTheColher/Capes#102]
cape not showing
instead of a cape, the inscription "update your mod", but the version of the mod is the latest (1.5.2 for now)
![image](https://github.com/CaelTheColher/Capes/assets/91954858/2d414d08-1af4-43e2-9124-8ad233192453)

**Comment by CaelTheColher** [comment]
MinecraftCapes updated their API and now started serving that cape to the old API which the 1.19 version of Capes uses. I'm releasing a fix for it and it should be uploaded to the usual platforms soon.

**Comment by Revod** [comment]
Hello @CaelTheColher  , this problem was update from what I see in my mudpack, but Im using minecraftcapes and still can't see my cape here are the examples


![](https://cdn.discordapp.com/attachments/880133918567845958/1130345689843515422/Screenshot_2023-07-16_at_10.50.08_PM.png)

and this inside of my 1.20.1 world
![](https://media.discordapp.net/attachments/880133918567845958/1130346193084502046/Screenshot_2023-07-16_at_10.52.09_PM.png?width=2046&height=1332)
